### ISSUE TITLE
Swift 3 issues

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#107] opened 2016-08-04 23:21 UTC
Checked on Xcode 8 beta 4
- [x] Resolving an instance that has `weak` properties that are not `NSObject` subclasses causes a crash.
  https://bugs.swift.org/browse/SR-2144
  Workaround: make your `weak` properties subclasses of `NSObject` or do not use `weak` property attribute.
- [x] Resolving an instance that has IUO properties causes a crash.
  https://bugs.swift.org/browse/SR-2282
  Workaround: use optional properties instead of IUO properties in instances resolved by container.
- [ ] Container is not able to use factories registered with IUO runtime arguments.
  https://bugs.swift.org/browse/SR-2143
  Workaround: do not use IUO as argument type when registering and resolving components
- [ ] Swift compiler may generate warnings when using auto-injection (#139)
  https://bugs.swift.org/browse/SR-2921
- [ ] Swift does not correctly distinguishes between functions accepting single tuple parameter and functions accepting several parameters of tuple elements types, leading to wrong `register` method calls (see #147 for details). Should be fixed for Swift 4 with [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md)

**Comment by KelvinJin** [comment] 2016-09-21 08:13
Hmm, damn these issues. The second issue almost makes ViewController with IBOutlet unresolvable? Sigh...

**Comment by ilyapuchka** [comment] 2016-10-07 17:25
@KelvinJin good news are that first issue is not happening any more in Xcode 8 GM. Bad news are that the second one is still there. So I've just hot patched auto-injection to avoid accessing IUO properties. So it should be possible to use IUO again for outlets after it is merged

**Comment by ilyapuchka** [comment] 2016-10-07 20:14
I will keep this issue opened to keep track of the Swift team progress

**Comment by KelvinJin** [comment] 2016-10-09 09:44
@ilyapuchka Great! After I updated my project to Swift 3, I was looking for DI library to replace Typhoon (Typhoon was good for Swift 1, but not working for 3 anymore) And I found this. Frankly speaking, this is the best DI library for Swift 3 or even Swift. Well done!

**Comment by sc0rch** [comment] 2016-10-10 07:39
I still have the random crashes with latest version of Dip and Xcode 8. Something like that:
<img width="720" alt="dip_swift_3_crash" src="https://cloud.githubusercontent.com/assets/2544587/19229330/71644b60-8ed5-11e6-9333-8c603b30c496.png">

**Comment by ilyapuchka** [comment] 2016-10-10 08:01
Hi @sc0rch ! Can you provide more details on what properties do you have in the object that is being resolved when you got the crash?

**Comment by ilyapuchka** [comment] 2016-10-10 08:07
One option that I see to completely work around those issues is to make auto-injection and resolving properties using `resolvingProperties` method mutually exclusive.

**Comment by sc0rch** [comment] 2016-10-10 08:20
Hi, @ilyapuchka !
It happens while creating and injecting the Interactor:
```
class EditUserNameInteractor: EditUserNameInteractorInput {
  // this code works
  private let _output = InjectedWeak<EditUserNameInteractorOutput>()
  var output: EditUserNameInteractorOutput? { return _output.value }

  unowned let userDataManager: UserDataManagerInterface
  unowned let apiClient: ApiClientInterface

  // if to comment out the constructor arguments, it works without crash
  init(userDataManager: UserDataManagerInterface, apiClient: ApiClientInterface) {
    self.userDataManager = userDataManager
    self.apiClient = apiClient
  }

  ...
}

let dipRoot = DependencyContainer() { root in
  root.register(.singleton) {
    LocalDataStore()
      as LocalDataStoreInterface
  }
  root.register(.singleton) {
    ViewerSessionManager(localDataStore: $0)
      as ViewerSessionManagerInterface
  }
  root.register(.singleton) {
    ApiClient(viewerSessionManager: $0)
      as ApiClientInterface
  }
  root.register(.singleton) {
    UserDataManager(localDataStore: $0, apiClient: $1)
      as UserDataManagerInterface
  }

  ...
  editUserNameModule.collaborate(with: root)
}

let editUserNameModule = DependencyContainer() { container in
  ...
  let interactor = container.register(.shared) {
    try EditUserNameInteractor(userDataManager: $0, apiClient: $1)
      as EditUserNameInteractorInput
  }
  ...
}
```

All protocol are subclasses of ``class``
Maybe crash happens while injecting contructor arguments.
I have the same interactor structure, and it has NO ISSUES, it is so frustrating:
```
class LoginInteractor: LoginInteractorInput {
  //
  // MARK: - Dependencies
  //
  private let _output = InjectedWeak<LoginInteractorOutput>()
  var output: LoginInteractorOutput? { return _output.value }
  
  unowned let viewerSessionManager: ViewerSessionManagerInterface
  unowned let apiClient: ApiClientInterface

  init(viewerSessionManager: ViewerSessionManagerInterface, apiClient: ApiClientInterface) {
    self.viewerSessionManager = viewerSessionManager
    self.apiClient = apiClient
  }
  ...
}
```

Sorry if there is my mistake anywere, I'm newbie in iOS DI.

**Comment by ilyapuchka** [comment] 2016-10-10 08:24
Thanks, I'll try to reproduce. Your comment "if to comment out the constructor arguments, it works without crash" makes it look like there is some other issues I haven't faced in tests.

**Comment by sc0rch** [comment] 2016-10-10 08:28
Possible workaround as you said earlier: auto injection. This code works as intended:
```
class EditUserNameInteractor: EditUserNameInteractorInput {
  private let _output = InjectedWeak<EditUserNameInteractorOutput>()
  var output: EditUserNameInteractorOutput? { return _output.value }
  
  private let _apiClient = InjectedWeak<ApiClientInterface>()
  var apiClient: ApiClientInterface? { return _apiClient.value }
  
  private let _userDataManager = InjectedWeak<UserDataManagerInterface>()
  var userDataManager: UserDataManagerInterface? { return _userDataManager.value }
  
  ...
```

**Comment by ilyapuchka** [comment] 2016-10-10 09:06
@sc0rch can not reproduce the same right away, but I'm glad that auto-injection way works.
I guess it fails on mirroring your `EditUserNameInteractor` but I don't see right away what causes it. Do you get any message on crash?

**Comment by sc0rch** [comment] 2016-10-10 09:18
@ilyapuchka I don't see any messages, sorry, only the exception in the debugger log (as on screenshot). I have tried Product -> Clean, but it is not much helping.
I'm in process of deep refactoring, if I find some clues, I'll post them here.

**Comment by ilyapuchka** [comment] 2016-10-10 09:47
@sc0rch  Can you also show how EditUserNameViewPresenter is defined?

**Comment by sc0rch** [comment] 2016-10-10 09:53
@ilyapuchka 
Project has dosens of modules, but here is the code:
```
class EditUserNameViewPresenter: EditUserNameModuleInterface, EditUserNameInteractorOutput {
  // [strong] wireframe
  private let _editUserNameWireframe = Injected<EditUserNameWireframe>()
  var editUserNameWireframe: EditUserNameWireframe? { return _editUserNameWireframe.value }

  // [strong] interactor
  private let _editUserNameInteractor = Injected<EditUserNameInteractorInput>()
  var editUserNameInteractor: EditUserNameInteractorInput? { return _editUserNameInteractor.value }

  // [weak] view
  private let _editUserNameInterface = InjectedWeak<EditUserNameViewInterface>()
  var editUserNameInterface: EditUserNameViewInterface? { return _editUserNameInterface.value }

  ...}

class ModuleWireframe {
  ...
}
class EditUserNameWireframe: ModuleWireframe {
  // [weak] presenters
  private let _editUserNameViewPresenter = InjectedWeak<EditUserNameViewPresenter>()
  var editUserNameViewPresenter: EditUserNameViewPresenter? { return _editUserNameViewPresenter.value }

  // [weak] views
  private let _editUserNameViewController = InjectedWeak<EditUserNameViewController>()
  var editUserNameViewController: EditUserNameViewController? { return _editUserNameViewController.value }

  ...
}
```

**Comment by ilyapuchka** [comment] 2016-10-10 09:55
@sc0rch Thanks! So you use auto-injection almost everywhere and still got the crash? Do you have any other properties defined on `EditUserNameViewPresenter` except injected?

**Comment by sc0rch** [comment] 2016-10-10 10:55
@ilyapuchka 
I found another frustrating issue, here the module definition:
```
let editUserEmailModule = DependencyContainer() { container in
  // EditUserEmailWireframe
  let editUserEmailWireframe = container.register(.weakSingleton) {
    EditUserEmailWireframe()
      as EditUserEmailWireframe
  }
  
  // EditUserEmailInteractor
  let editUserEmailInteractor = container.register(.weakSingleton) {
    EditUserEmailInteractor()
      as EditUserEmailInteractorInput
  }
  
  // ConfirmUserEmailInteractor
  let confirmUserEmailInteractor = container.register(.weakSingleton) {
    ConfirmUserEmailInteractor()
      as ConfirmUserEmailInteractorInput
  }
  
  // EditUserEmailViewPresenter
  let editUserEmailViewPresenter = container.register(.weakSingleton) {
    EditUserEmailViewPresenter()
      as EditUserEmailViewPresenter
  }
  container.register(editUserEmailViewPresenter, type: EditUserEmailModuleInterface.self)
  container.register(editUserEmailViewPresenter, type: EditUserEmailInteractorOutput.self)
  container.register(editUserEmailViewPresenter, type: ConfirmUserEmailInteractorOutput.self)
  
  // EditUserEmailViewController
  let editUserEmailViewController = container.register(.weakSingleton) {
    EditUserEmailViewController(nibName: "EditUserEmailViewController", bundle: nil)
      as EditUserEmailViewController
  }
  container.register(editUserEmailViewController, type: EditUserEmailViewInterface.self)

  // ConfirmUserEmailViewController
  let confirmUserEmailViewController = container.register(.weakSingleton) {
    ConfirmUserEmailViewController(nibName: "ConfirmUserEmailViewController", bundle: nil)
      as ConfirmUserEmailViewController
  }
  container.register(confirmUserEmailViewController, type: ConfirmUserEmailViewInterface.self)
}
```

I'm receiving the error:
```
Reusing previously resolved instance Dip.WeakBox<Any>
Could not cast value of type 'Dip.WeakBox<Any>' (0x1223b31d0) to 'MobitrackClientApp.EditUserEmailViewController' (0x10bd79020).
```

If I'll change ``.weakSingleton`` to ``.shared``, crash be gone, but code will start to recreate some modules instead of reusing. Maybe I don't understand clearly how collaboration and scopes works together.

<img width="720" alt="dip_could_not_cast" src="https://cloud.githubusercontent.com/assets/2544587/19233760/41d4e768-8ef0-11e6-9c66-832bb9d46ba3.png">

**Comment by ilyapuchka** [comment] 2016-10-10 10:57
@sc0rch can you please create a separate issue for that? I doubt that it has to do anything with Swift 3. Thanks!

**Comment by sc0rch** [comment] 2016-10-11 13:45
@ilyapuchka Hello again!
We forgot to add strong reference to container into AppDelegate.
I believe, it is the main reason of random crashes and issues during the process of DI integration.

**Comment by leandromperez** [comment] 2017-04-12 19:22
Hello,
First of all, thanks for working on DIP. It is a great tool, I am really enjoying it. 

I am writing to you guys because I am having an issue. Perhaps someone can help me out.

I am facing a EXC_BAD_ACCESS when DIP tries to resolve the first dependency. It happens in the AppDelegate when launching the app. 
The weird thing is that it only occurs when I run the app on my device. It doesn't happen in the simulator.

![screen shot 2017-04-12 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/104836/24975145/0980c742-1f9b-11e7-9dad-e81fe9346e44.png)

I am working with XCode 8.2.1, running on an iPad MD328LE/A iOS 9.3.5

Could this be related to any of the known issues? 
Any ideas ?

**Comment by ilyapuchka** [comment] 2017-04-12 19:40
Hi, @leandromperez I would suggest to update your Xcode to the latest version first of all and check if it's still happens. If it does please post the console log (setting Dip logLevel to verbose) and post it in new issue, that will help to hunt it. From what I can see in the stack trace it's caused by reflection that can be one of the bugs listed at the top.
Btw do you hold a strong reference to the container that you have in `AppDependencies`? Asking because that was the reason of one issue discussed here before.

**Comment by leandromperez** [comment] 2017-04-13 12:22
Hi @ilyapuchka,
Thanks for your reply. I have updated Xcode and the problem is still there. The simulator works just fine, my iPad crashes.
I am holding a strong reference to the container AppDelegate->AppDependencies->Container
I will post it in a new issue.

**Comment by njall1** [comment] 2017-05-18 14:44
Привет, я создал такой контейнер:
func configureRootModule(container rootContainer: DependencyContainer) {
        rootContainer.register(.weakSingleton, factory: RootPresenter.init)
            .implements(AnyObject.self,
                        RootModuleInput.self,
                        AppDelegateOutput.self,
                        RootInteractorOutput.self)
            .resolvingProperties { container, presenter in
                presenter.delegate = UIApplication.shared.delegate as! AppDelegate
                presenter.router = try! container.resolve()
                presenter.interactor = try! container.resolve()
                presenter.deeplinkHandler = try! container.resolve()
                presenter.shortcutHandler = try! container.resolve()
        }
        
        rootContainer.register(.weakSingleton) { RootInteractor() }
            .implements(RootInteractorInput.self)
            .resolvingProperties { container, interactor in
                interactor.serviceLocator = try! container.resolve()
                interactor.output = try! container.resolve()
                interactor.pinKeeperService = try! container.resolve()
                interactor.sessionManager = try! container.resolve()
                interactor.authorizationService = try! container.resolve()
                interactor.commonDataService = try! container.resolve()
                interactor.mockAuthorizationService = try! container.resolve()
        }
        
        rootContainer.register(.weakSingleton) { RootRouter() as RootRouterInput }
        
        rootContainer.register(.weakSingleton) { ServiceLocator() }
            .resolvingProperties { container, adapter in
                adapter.currenciesResolver = try! container.resolve()
        }
    }

Но в основном использую scope : .shared.

Как такое может быть если RootPresenter и RootInteractor регистрируются со scope = weakSingleton.
![screen shot 2017-05-18 at 17 43 39](https://cloud.githubusercontent.com/assets/9320927/26207883/68821940-3bf1-11e7-8e0c-3aa6b997f572.png)

**Comment by ilyapuchka** [comment] 2017-05-18 20:10
@njall1 Please create a new issue to discuss that.

**Comment by ilyapuchka** [comment] 2017-07-23 19:52
Planning to close this as soon as will have chance to run against with Swift 4

**Closed** 2018-04-05 23:44 UTC
