### ISSUE TITLE
Collaborators not honoring singleton

### ISSUE THREAD

**Issue by jtwigg** [AliSoftware/Dip#148] opened 2017-04-03 01:00 UTC
I intend to have a root container and then possibly several mutually exclusive dependent containers. The root will naturally have several .singleton's, but I'm seeing a test I wrote as a scouting mission for dip fail, and I think its unexpected. <see below>

It seems that collaborator2 honors the singleton pattern, but collaborator1 gets the shaft, likely because of some ordering problem. I tried several permutations, to no avail.

``` 
  func testCollaborationFailure() {

    let container = DependencyContainer()
    container.register(.singleton){ ResolvableService() as Service }

    //when
    let collaborator1 = DependencyContainer()
    let collaborator2 = DependencyContainer()

    collaborator1.collaborate(with: container)
    collaborator2.collaborate(with: container)

    let service1 = try! collaborator1.resolve() as Service
    let service2 = try! collaborator2.resolve() as Service
    let serviceRoot = try! container.resolve() as Service

    XCTAssertTrue(service1 === service2) #<<< FAIL
    XCTAssertTrue(service1 === serviceRoot) #<<<< FAIL
    XCTAssertTrue(service2 === serviceRoot) # Success!
  }
```

**Comment by ilyapuchka** [comment] 2017-04-03 20:59
Hi @jtwigg! Thanks for reporting that, seems like the issue in the logic around resolving with collaboration. Until it is fixed I can suggest you a workaround to do `collaborator2.collaborate(with: container, collaborator1)`

**Comment by ilyapuchka** [comment] 2017-04-03 21:04
Basically the issue is caused by the fact that when describing collaboration we override a reference to singletons collection in containers passed as arguments. So after second call to `collaborate` `container` and `collaborator2` will share this collection, but `container` and `collaborator1` will not any more.

**Closed** 2017-04-06 20:40 UTC
Labels: bug
